apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: abhishekkumar0301/gitops-1:
03c8cbc7da8ee097fa59a756c686fb47227f0373
    ports:
    - containerPort: 80
